"""Shared pipeline and rendering helpers for all tool-specific exporters."""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path

from contextos import __version__
from contextos.core.context_selector import (
    ContextSelection,
    SelectionConfig,
    _load_graph_safe,
    _load_summaries_safe,
    _load_text_safe,
    _select,
)
from contextos.core.pack_builder import _build_dep_notes, _ensure_scan, _is_test_file

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------


@dataclass
class ExportConfig:
    budget: int = 8000
    include_tests: bool = True
    no_source: bool = False
    add_timestamp: bool = True
    allow_sensitive: bool = False  # if True, skip secret redaction (dangerous)


# ---------------------------------------------------------------------------
# Public pipeline
# ---------------------------------------------------------------------------


def build_export(
    task: str,
    repo_root: Path,
    contextos_dir: Path,
    renderer: Callable[..., str],
    output_filename: str,
    *,
    config: ExportConfig | None = None,
) -> tuple[str, ContextSelection]:
    """Scan, select, render, and write a tool-specific context file.

    Returns (rendered_content, selection). Writes to contextos_dir/output_filename.
    """
    cfg = config or ExportConfig()

    _ensure_scan(repo_root, contextos_dir)

    summaries = _load_summaries_safe(contextos_dir)
    if not cfg.include_tests:
        summaries = {p: s for p, s in summaries.items() if not _is_test_file(p)}

    graph = _load_graph_safe(contextos_dir)
    memory = _load_text_safe(contextos_dir / "MEMORY.md")

    sel_cfg = SelectionConfig(
        budget=cfg.budget,
        no_source=cfg.no_source,
        allow_sensitive=cfg.allow_sensitive,
    )
    selection = _select(task, summaries, graph, memory, repo_root, sel_cfg)

    project_summary = _load_text_safe(contextos_dir / "PROJECT_INDEX.md")
    decisions = _load_text_safe(contextos_dir / "DECISIONS.md")
    ts = datetime.now(tz=UTC).isoformat(timespec="seconds") if cfg.add_timestamp else ""
    dep_notes = _build_dep_notes(selection, graph)

    content = renderer(task, project_summary, decisions, selection, dep_notes, ts)

    contextos_dir.mkdir(parents=True, exist_ok=True)
    (contextos_dir / output_filename).write_text(content, encoding="utf-8")

    return content, selection


# ---------------------------------------------------------------------------
# Shared renderer
# ---------------------------------------------------------------------------


def render_context(
    task: str,
    project_summary: str,
    decisions: str,
    selection: ContextSelection,
    dep_notes: str,
    timestamp: str,
    *,
    tool_name: str,
    filename: str,
    usage_note: str,
    agent_instructions: str,
    allow_sensitive: bool = False,
) -> str:
    """Render a tool-specific context pack in Markdown."""
    parts: list[str] = []

    # Header
    header_lines = [
        f"# {tool_name} Context",
        "",
        f"> Generated by ContextOS for **{tool_name}**.",
    ]
    if timestamp:
        header_lines += [f"> Generated: {timestamp}"]
    if allow_sensitive:
        header_lines += [
            "> ⚠️  **WARNING: --allow-sensitive is active. Secrets may be present.**",
        ]
    header_lines += [f"> Usage: {usage_note}", ""]
    parts.append("\n".join(header_lines))

    # Secret redaction notice
    if selection.secret_warnings and not allow_sensitive:
        n = len(selection.secret_warnings)
        parts.append(
            f"> ⚠️  **{n} secret(s) detected and redacted** "
            f"(replaced with `[REDACTED_*]` tokens).\n\n"
        )

    # Task
    parts.append(_section("Current Task", task.strip()))

    # Project overview
    if project_summary.strip():
        parts.append(_section("Project Overview", _trim(project_summary, 600)))

    # Decisions
    if decisions.strip():
        parts.append(_section("Relevant Decisions", _trim(decisions, 400)))

    # Context files
    if selection.selected:
        file_lines: list[str] = []
        for result in selection.selected:
            reasons = "; ".join(result.reasons) if result.reasons else "no specific match"
            file_lines += [
                f"### `{result.rel_path}` ({result.kind})",
                "",
                f"*Score: {result.score:.2f} — {reasons}*",
                "",
                result.content,
                "",
            ]
        parts.append(_section("Context Files", "\n".join(file_lines)))
    else:
        parts.append(_section("Context Files", "*No files selected within budget.*"))

    # Dependency notes
    if dep_notes.strip():
        parts.append(_section("Dependency Notes", dep_notes))

    # Token budget table
    budget_rows = [
        "| Metric | Value |",
        "|--------|-------|",
        f"| Budget | {selection.budget:,} tokens |",
        f"| Used | {selection.used_tokens:,} tokens |",
        f"| Files selected | {len(selection.selected)} |",
        f"| Files excluded | {len(selection.excluded)} |",
    ]
    parts.append(_section("Token Budget", "\n".join(budget_rows)))

    # Excluded files
    if selection.excluded:
        excl_rows = ["| File | Note |", "|------|------|"]
        for p in selection.excluded:
            note = "secret/credential file" if _looks_secret(p) else "over budget"
            excl_rows.append(f"| `{p}` | {note} |")
        parts.append(_section("Excluded Files", "\n".join(excl_rows)))

    # Tool-specific instructions
    parts.append(_section(f"{tool_name} Instructions", agent_instructions))

    # Footer
    parts.append(f"---\n*Generated by ContextOS v{__version__} for {tool_name}*\n")

    return "\n".join(parts)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _section(title: str, body: str) -> str:
    return f"## {title}\n\n{body.rstrip()}\n\n"


def _trim(text: str, max_chars: int) -> str:
    if len(text) <= max_chars:
        return text
    return text[:max_chars].rsplit("\n", 1)[0] + "\n\n*[trimmed for token budget]*"


def _looks_secret(rel_path: str) -> bool:
    name = Path(rel_path).name.lower()
    return name.startswith(".env") or "secret" in name or "credential" in name or "password" in name
